-- Lisää DROP TABLE lauseet tähän tiedostoon

DROP TABLE IF EXISTS Gbuser CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Ticket CASCADE;
DROP TABLE IF EXISTS Bet CASCADE;
DROP TABLE IF EXISTS Betticket CASCADE;